"""
Report generation engine.
Transforms ScanResult into human-readable audit reports.
"""

from pathlib import Path
from typing import Dict
from core.models.scan_result import ScanResult


SEVERITY_ICONS = {
    "CRITICAL": "🔴",
    "HIGH": "🟠",
    "MEDIUM": "🟡",
    "LOW": "🔵",
    "INFO": "🟢",
}


def _render_template(template_path: str, data: Dict) -> str:
    """Simple template renderer — replaces {{ key }} with values."""
    with open(template_path, 'r', encoding='utf-8') as f:
        template = f.read()

    # Simple variable substitution
    for key, value in data.items():
        placeholder = f"{{{{ {key} }}}}"
        if placeholder in template:
            template = template.replace(placeholder, str(value))

    return template


def build_audit_report(scan_result: ScanResult, template_path: str = None) -> str:
    """
    Build audit report from ScanResult.
    Uses simple template substitution (no external deps).
    """
    if template_path is None:
        template_path = str(Path(__file__).parent / "templates" / "audit_v1.md")

    findings_data = []
    for f in scan_result.findings:
        fd = f.to_dict()
        fd["severity_icon"] = SEVERITY_ICONS.get(fd["severity"], "⚪")
        findings_data.append(fd)

    # Build active risk paths as markdown list
    risk_paths = scan_result.active_risk_paths()
    risk_md = "
".join(f"- {rp}" for rp in risk_paths.keys()) if risk_paths else "None"

    data = {
        "url": scan_result.url,
        "final_url": scan_result.final_url,
        "status_code": scan_result.status_code,
        "timestamp": scan_result.timestamp,
        "severity_score": scan_result.severity_score(),
        "total_issues": scan_result.total_issues(),
        "critical": scan_result.critical_count(),
        "high": scan_result.high_count(),
        "medium": scan_result.medium_count(),
        "low": scan_result.low_count(),
        "active_risk_paths": risk_md,
        "findings": findings_data,
    }

    # Manual template building (no Jinja dependency)
    lines = [
        f"# Security Header Audit Report",
        f"",
        f"**Target:** `{scan_result.url}`  ",
        f"**Final URL:** `{scan_result.final_url}`  ",
        f"**Status Code:** {scan_result.status_code}  ",
        f"**Scan Timestamp:** {scan_result.timestamp}  ",
        f"**Tool:** HeaderShield v2.0.0  ",
        f"**Scan Type:** Passive Header Audit  ",
        f"",
        f"---",
        f"",
        f"## Executive Summary",
        f"",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| Severity Score | {scan_result.severity_score()} |",
        f"| Total Issues | {scan_result.total_issues()} |",
        f"| Critical (P0) | {scan_result.critical_count()} |",
        f"| High (P1) | {scan_result.high_count()} |",
        f"| Medium (P2) | {scan_result.medium_count()} |",
        f"| Low (P3) | {scan_result.low_count()} |",
        f"",
    ]

    if risk_paths:
        lines.extend([
            f"### Active Risk Paths",
            f"",
        ])
        for rp in risk_paths:
            lines.append(f"- {rp}")
        lines.append(f"")

    lines.extend([
        f"---",
        f"",
        f"## Findings",
        f"",
    ])

    for f in scan_result.findings:
        icon = SEVERITY_ICONS.get(f.severity.value, "⚪")
        lines.extend([
            f"### {icon} {f.header_name}",
            f"",
            f"- **Status:** {f.status.value}",
            f"- **Severity:** {f.severity.value}",
            f"- **Current Value:** `{f.current_value or 'N/A'}`",
            f"- **Expected:** `{f.expected_value or 'N/A'}`",
            f"",
            f"**Risk Path:** {f.risk_path}",
            f"",
            f"**Evidence:**",
            f"```",
            f"{f.evidence}",
            f"```",
            f"",
            f"**Recommendation:**",
            f"```",
            f"{f.recommendation}",
            f"```",
            f"",
            f"---",
            f"",
        ])

    lines.extend([
        f"## Reproducibility",
        f"",
        f"```bash",
        f"# Reproduce this scan",
        f"curl -I -L "{scan_result.final_url}"",
        f"```",
        f"",
        f"---",
        f"",
        f"*Report generated by HeaderShield v2.0.0 — Passive Security Header Audit Tool*",
    ])

    return "
".join(lines)


def save_report(report: str, url: str, output_dir: str = "outputs/reports") -> Path:
    """Save markdown report to disk."""
    from pathlib import Path
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)

    safe_name = url.replace("https://", "").replace("http://", "").replace("/", "_")
    filepath = out / f"{safe_name}_audit.md"

    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(report)

    return filepath
