"""
Report generation engine with redirect awareness and confidence scoring.
"""

from pathlib import Path
from typing import Dict, Optional
from headershield.core.models.scan_result import ScanResult


SEVERITY_ICONS = {
    "CRITICAL": "🔴",
    "HIGH": "🟠",
    "MEDIUM": "🟡",
    "LOW": "🔵",
    "INFO": "🟢",
}


def build_audit_report(scan_result: ScanResult, raw_response: Optional[Dict] = None) -> str:
    """
    Build audit report from ScanResult with redirect chain and confidence.
    """
    risk_paths = scan_result.active_risk_paths()
    redirect_count = raw_response.get("redirect_count", 0) if raw_response else 0
    
    lines = [
        "# Security Header Audit Report",
        "",
        f"**Target:** `{scan_result.url}`  ",
        f"**Final URL:** `{scan_result.final_url}`  ",
        f"**Status Code:** {scan_result.status_code}  ",
        f"**Scan Timestamp:** {scan_result.timestamp}  ",
        f"**Tool:** HeaderShield v2.1.0  ",
        f"**Scan Type:** Passive Header Audit  ",
    ]
    
    if redirect_count > 0:
        lines.append(f"**Redirects Detected:** {redirect_count}  ")
    
    lines.extend([
        "",
        "---",
        "",
        "## Executive Summary",
        "",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| Severity Score | {scan_result.severity_score()} |",
        f"| Total Issues | {scan_result.total_issues()} |",
        f"| Critical (P0) | {scan_result.critical_count()} |",
        f"| High (P1) | {scan_result.high_count()} |",
        f"| Medium (P2) | {scan_result.medium_count()} |",
        f"| Low (P3) | {scan_result.low_count()} |",
        "",
    ])
    
    if risk_paths:
        lines.extend([
            "### Active Risk Paths",
            "",
        ])
        for rp in risk_paths:
            lines.append(f"- {rp}")
        lines.append("")
    
    # Redirect chain section
    if raw_response and raw_response.get("redirect_chain"):
        lines.extend([
            "### Redirect Chain",
            "",
            "| Step | URL | Status |",
            "|------|-----|--------|",
        ])
        for hop in raw_response["redirect_chain"]:
            lines.append(f"| {hop['step']} | `{hop['url']}` | {hop['status_code']} |")
        lines.append("")
    
    lines.extend([
        "---",
        "",
        "## Findings",
        "",
    ])
    
    for f in scan_result.findings:
        icon = SEVERITY_ICONS.get(f.severity.value, "⚪")
        
        # Extract confidence from evidence if present
        confidence = "HIGH"
        if "Confidence:" in f.evidence:
            try:
                confidence = f.evidence.split("Confidence:")[1].split(".")[0].strip()
            except:
                pass
        
        lines.extend([
            f"### {icon} {f.header_name}",
            "",
            f"- **Status:** {f.status.value}",
            f"- **Severity:** {f.severity.value}",
            f"- **Confidence:** {confidence}",
            f"- **Current Value:** `{f.current_value or 'N/A'}`",
            f"- **Expected:** `{f.expected_value or 'N/A'}`",
            "",
            f"**Risk Path:** {f.risk_path}",
            "",
            "**Evidence:**",
            "```",
            f"{f.evidence}",
            "```",
            "",
            "**Recommendation:**",
            "```",
            f"{f.recommendation}",
            "```",
            "",
            "---",
            "",
        ])
    
    lines.extend([
        "## Reproducibility",
        "",
        "```bash",
        f"# Reproduce this scan",
        f'curl -I -L "{scan_result.final_url}"',
        "```",
        "",
        "---",
        "",
        "*Report generated by HeaderShield v2.1.0 — Passive Security Header Audit Tool*",
    ])
    
    return "\n".join(lines)


def save_report(report: str, url: str, output_dir: str = "outputs/reports") -> Path:
    """Save markdown report to disk."""
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)
    
    safe_name = url.replace("https://", "").replace("http://", "").replace("/", "_")
    filepath = out / f"{safe_name}_audit.md"
    
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(report)
    
    return filepath
