"""
headershield.reports.markdown
Generate human-readable audit reports from scan results.
"""

from typing import Dict, List
from pathlib import Path
from datetime import datetime


SEVERITY_ICONS = {
    "CRITICAL": "🔴",
    "HIGH": "🟠",
    "MEDIUM": "🟡",
    "LOW": "🔵",
    "INFO": "🟢",
}


def generate_report(scan_result: Dict, output_path: str = None) -> str:
    """
    Generate a markdown audit report from a single scan result.
    """
    url = scan_result.get("url", "Unknown")
    status = scan_result.get("status_code", "N/A")
    timestamp = scan_result.get("timestamp", datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC"))

    lines = [
        f"# Security Header Audit Report",
        f"",
        f"**Target:** `{url}`  ",
        f"**Status:** {status}  ",
        f"**Timestamp:** {timestamp}  ",
        f"**Tool:** HeaderShield v1.0.0  ",
        f"",
        f"---",
        f"",
    ]

    if "error" in scan_result:
        lines.extend([
            f"## ⚠️ Scan Error",
            f"",
            f"```",
            f"{scan_result['error']}",
            f"```",
            f"",
        ])
        report = "
".join(lines)
        if output_path:
            Path(output_path).write_text(report, encoding='utf-8')
        return report

    # Risk Summary
    risk_summary = scan_result.get("risk_summary", {})
    active_risks = risk_summary.get("active_risk_paths", {})
    severity_count = risk_summary.get("severity_count", {})
    total_issues = risk_summary.get("total_issues", 0)

    lines.extend([
        f"## Risk Summary",
        f"",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| Total Issues | {total_issues} |",
        f"| Critical | {severity_count.get('CRITICAL', 0)} |",
        f"| High | {severity_count.get('HIGH', 0)} |",
        f"| Medium | {severity_count.get('MEDIUM', 0)} |",
        f"| Low | {severity_count.get('LOW', 0)} |",
        f"",
    ])

    if active_risks:
        lines.extend([
            f"### Active Risk Paths",
            f"",
        ])
        for risk, count in active_risks.items():
            lines.append(f"- {risk}")
        lines.append(f"")

    lines.extend([
        f"---",
        f"",
        f"## Findings",
        f"",
    ])

    # Sort findings by severity
    severity_order = {"CRITICAL": 0, "HIGH": 1, "MEDIUM": 2, "LOW": 3, "INFO": 4}
    findings = scan_result.get("findings", [])

    # Convert findings to dict if they're objects
    if findings and hasattr(findings[0], 'severity'):
        findings = [
            {
                "header": f.header_name,
                "present": f.present,
                "value": f.value,
                "expected": f.expected,
                "severity": f.severity.value,
                "risk_paths": [rp.value for rp in f.risk_paths],
                "remediation": f.remediation,
                "evidence": f.evidence,
            }
            for f in findings
        ]

    findings.sort(key=lambda x: severity_order.get(x.get("severity", "INFO"), 99))

    for finding in findings:
        sev = finding.get("severity", "INFO")
        icon = SEVERITY_ICONS.get(sev, "⚪")
        header = finding.get("header", "Unknown")
        present = "✅ Present" if finding.get("present") else "❌ Missing"
        value = finding.get("value") or "N/A"

        lines.extend([
            f"### {icon} {header}",
            f"",
            f"- **Status:** {present}",
            f"- **Current Value:** `{value}`",
            f"- **Expected:** `{finding.get('expected', 'N/A')}`",
            f"- **Severity:** {sev}",
            f"",
        ])

        if finding.get("risk_paths"):
            lines.append(f"**Risk Paths:**")
            for rp in finding["risk_paths"]:
                lines.append(f"- {rp}")
            lines.append(f"")

        lines.extend([
            f"**Remediation:**",
            f"```",
            f"{finding.get('remediation', 'N/A')}",
            f"```",
            f"",
            f"**Evidence:**",
            f"```",
            f"{finding.get('evidence', 'N/A')}",
            f"```",
            f"",
            f"---",
            f"",
        ])

    # Footer
    lines.extend([
        f"",
        f"## Reproducibility",
        f"",
        f"```bash",
        f"# Re-run this scan",
        f"python -m headershield scan {url}",
        f"```",
        f"",
        f"---",
        f"",
        f"*Report generated by HeaderShield — lightweight security header audit tool.*",
    ])

    report = "
".join(lines)

    if output_path:
        Path(output_path).write_text(report, encoding='utf-8')
        print(f"Report saved: {output_path}")

    return report


def generate_batch_report(summary_path: str, output_path: str = None) -> str:
    """
    Generate a comparative report from a batch scan summary.
    """
    import json

    with open(summary_path, 'r', encoding='utf-8') as f:
        summary = json.load(f)

    lines = [
        f"# Batch Security Header Audit Report",
        f"",
        f"**Total Scanned:** {summary.get('total_scanned', 0)}  ",
        f"**Successful:** {summary.get('successful', 0)}  ",
        f"**Failed:** {summary.get('failed', 0)}  ",
        f"**Tool:** HeaderShield v1.0.0  ",
        f"",
        f"---",
        f"",
        f"## Per-Target Summary",
        f"",
        f"| Target | Status | Issues | Critical | High | Medium | Low |",
        f"|--------|--------|--------|----------|------|--------|-----|",
    ]

    for result in summary.get("results", []):
        url = result.get("url", "Unknown")

        if "error" in result:
            lines.append(f"| `{url}` | ❌ Error | - | - | - | - | - |")
            continue

        risk = result.get("risk_summary", {})
        sev = risk.get("severity_count", {})
        issues = risk.get("total_issues", 0)

        lines.append(
            f"| `{url}` | ✅ {result.get('status_code', 'OK')} | {issues} | "
            f"{sev.get('CRITICAL', 0)} | {sev.get('HIGH', 0)} | {sev.get('MEDIUM', 0)} | {sev.get('LOW', 0)} |"
        )

    lines.extend([
        f"",
        f"---",
        f"",
        f"*Batch report generated by HeaderShield.*",
    ])

    report = "
".join(lines)

    if output_path:
        Path(output_path).write_text(report, encoding='utf-8')
        print(f"Batch report saved: {output_path}")

    return report
