"""
headershield.reports.markdown
Generate human-readable audit reports from scan results (v2 model).
"""

from typing import Dict, List, Union
from pathlib import Path
from datetime import datetime

from headershield.core.models.scan_result import ScanResult
from headershield.core.models.finding import Finding
from headershield.core.enums.severity import Severity, SEVERITY_ORDER
from headershield.core.enums.status import Status


SEVERITY_ICONS = {
    "CRITICAL": "🔴",
    "HIGH": "🟠",
    "MEDIUM": "🟡",
    "LOW": "🔵",
    "INFO": "🟢",
}


def generate_report(scan_result: Union[ScanResult, Dict], output_path: str = None) -> str:
    """
    Generate a markdown audit report from a ScanResult (v2 model).
    Accepts either a ScanResult object or its dict representation.
    """
    if isinstance(scan_result, ScanResult):
        result = scan_result
    else:
        # Build a ScanResult from dict for backward compatibility
        findings = [
            Finding(
                url=f.get("url", ""),
                header_name=f.get("header_name", "Unknown"),
                status=Status(f.get("status", "missing")),
                severity=Severity(f.get("severity", "INFO")),
                risk_path=f.get("risk_path", ""),
                evidence=f.get("evidence", ""),
                recommendation=f.get("recommendation", ""),
                current_value=f.get("current_value"),
                expected_value=f.get("expected_value"),
            )
            for f in scan_result.get("findings", [])
        ]
        result = ScanResult(
            url=scan_result.get("url", "Unknown"),
            findings=findings,
            status_code=scan_result.get("status_code", 0),
            final_url=scan_result.get("final_url", ""),
            timestamp=scan_result.get("timestamp", ""),
        )

    url = result.url
    status = result.status_code
    timestamp = result.timestamp or datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")

    lines = [
        "# Security Header Audit Report",
        "",
        f"**Target:** `{url}`  ",
        f"**Final URL:** `{result.final_url}`  ",
        f"**Status:** {status}  ",
        f"**Timestamp:** {timestamp}  ",
        f"**Tool:** HeaderShield v2.0.0  ",
        "",
        "---",
        "",
    ]

    # Risk Summary
    risk_paths = result.active_risk_paths()
    lines.extend([
        "## Risk Summary",
        "",
        "| Metric | Value |",
        "|--------|-------|",
        f"| Total Issues | {result.total_issues()} |",
        f"| Critical (P0) | {result.critical_count()} |",
        f"| High (P1) | {result.high_count()} |",
        f"| Medium (P2) | {result.medium_count()} |",
        f"| Low (P3) | {result.low_count()} |",
        f"| Severity Score | {result.severity_score()} |",
        "",
    ])

    if risk_paths:
        lines.extend([
            "### Active Risk Paths",
            "",
        ])
        for risk, count in risk_paths.items():
            lines.append(f"- {risk}")
        lines.append("")

    lines.extend([
        "---",
        "",
        "## Findings",
        "",
    ])

    # Sort findings by severity
    sorted_findings = sorted(result.findings, key=lambda f: SEVERITY_ORDER.get(f.severity, 99))

    for finding in sorted_findings:
        sev = finding.severity.value
        icon = SEVERITY_ICONS.get(sev, "⚪")
        header = finding.header_name
        status_str = finding.status.value

        # Extract confidence from evidence if present
        confidence = "HIGH"
        if "Confidence:" in finding.evidence:
            try:
                confidence = finding.evidence.split("Confidence:")[1].split(".")[0].strip()
            except Exception:
                pass

        lines.extend([
            f"### {icon} {header}",
            "",
            f"- **Status:** {status_str}",
            f"- **Severity:** {sev}",
            f"- **Confidence:** {confidence}",
            f"- **Current Value:** `{finding.current_value or 'N/A'}`",
            f"- **Expected:** `{finding.expected_value or 'N/A'}`",
            "",
            f"**Risk Path:** {finding.risk_path}",
            "",
            "**Evidence:**",
            "```",
            f"{finding.evidence}",
            "```",
            "",
            "**Recommendation:**",
            "```",
            f"{finding.recommendation}",
            "```",
            "",
            "---",
            "",
        ])

    # Footer
    lines.extend([
        "",
        "## Reproducibility",
        "",
        "```bash",
        "# Re-run this scan",
        f"headershield scan {url}",
        "```",
        "",
        "---",
        "",
        "*Report generated by HeaderShield — lightweight security header audit tool.*",
    ])

    report = "\n".join(lines)

    if output_path:
        Path(output_path).write_text(report, encoding='utf-8')
        print(f"Report saved: {output_path}")

    return report


def generate_batch_report(summary_path: str, output_path: str = None) -> str:
    """
    Generate a comparative report from a batch scan summary.
    """
    import json

    with open(summary_path, 'r', encoding='utf-8') as f:
        summary = json.load(f)

    lines = [
        "# Batch Security Header Audit Report",
        "",
        f"**Total Targets:** {summary.get('total_targets', 0)}  ",
        f"**Successful:** {summary.get('successful', 0)}  ",
        f"**Failed:** {summary.get('failed', 0)}  ",
        f"**Timestamp:** {summary.get('batch_timestamp', 'N/A')}  ",
        f"**Tool:** HeaderShield v2.0.0  ",
        "",
        "---",
        "",
        "## Per-Target Summary",
        "",
        "| Target | Status | Issues | Critical | High | Medium | Low | Score |",
        "|--------|--------|--------|----------|------|--------|-----|-------|",
    ]

    for result in summary.get("results", []):
        url = result.get("url", "Unknown")

        if "error" in result:
            lines.append(f"| `{url}` | ❌ Error | - | - | - | - | - | - |")
            continue

        counts = result.get("issue_counts", {})
        score = result.get("severity_score", 0)

        lines.append(
            f"| `{url}` | ✅ {result.get('status_code', 'OK')} | "
            f"{counts.get('total', 0)} | "
            f"{counts.get('critical', 0)} | {counts.get('high', 0)} | "
            f"{counts.get('medium', 0)} | {counts.get('low', 0)} | {score} |"
        )

    lines.extend([
        "",
        "---",
        "",
        "*Batch report generated by HeaderShield.*",
    ])

    report = "\n".join(lines)

    if output_path:
        Path(output_path).write_text(report, encoding='utf-8')
        print(f"Batch report saved: {output_path}")

    return report
